### ISSUE TITLE
Code modernization

### ISSUE THREAD

**Issue by ghost** [dreamlayers/dpf-ax#2]
I recently came across this project and I was noticing how reliant it is on legacy tool-chains and libraries. I was thinking of trying to update the code to work with current software so you don't need to setup a legacy environment just to use it all.

Specifically, I noticed that these 3 things are an issue:
- libusb 0.1
- Python 2
- SDCC 2.9

@dreamlayers Would you be willing to accept PRs that attempt to address this?

**Comment by dreamlayers** [comment]
I've merged your commits for [Python 3](https://github.com/braewoods/dpf-ax/commit/6300a42735a13a4046b65fcd0ea7497cbad74468), [newer ffmpeg](https://github.com/braewoods/dpf-ax/commit/010dd19b07e30e08423db66a7fefe9f5c3903bc1) and [libusb-1.0](https://github.com/braewoods/dpf-ax/commit/3649723fecf45b9256e50d64a875545e7eddc33b). I'm still using SDCC 2.9.0, the binaries from sdcc-2.9.0-i386-unknown-linux2.5.tar.bz2.

I rarely use this and I'm not sure I've done enough testing, but the built firmware binaries didn't change, and I was able to install it on my acme_10 without problems. Thank you.
